version: "3.8"

services:
  postgres:
    container_name: spring_db
    image: postgres:latest
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5433:5432"
    volumes:
      - habrdb-data:/var/lib/postgresql/data

volumes:
  habrdb-data: